# Generated by Django 6.1 on 2026-08-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_ipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('shares', models.IntegerField(default=0)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.ipo')),
                ('pan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checker.pan')),
            ],
        ),
    ]
