# Generated by Django 6.1 on 2026-08-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_allotment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='registrar',
            field=models.CharField(default='KFintech', max_length=100),
            preserve_default=False,
        ),
    ]
