# Generated by Django 6.1 on 2026-08-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_ipo_registrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
