# Generated by Django 6.1 on 2026-08-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0005_ipo_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipo',
            name='client_id',
        ),
        migrations.AddField(
            model_name='pan',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
