# Generated by Django 6.1 on 2026-08-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0006_remove_ipo_client_id_pan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ipo',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
